Giving up on CodeQL
Kept saying this without telling me what file is causing trouble:

  [2021-06-16 00:43:50] [build-stderr] Only found JavaScript or TypeScript files that were empty or contained syntax errors.
  [2021-06-16 00:43:50] [build-stderr] Only found JavaScript or TypeScript files that were empty or contained syntax errors.
  Error: 6-16 00:43:50] [ERROR] Spawned process exited abnormally (code 255; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/javascript/tools/autobuild.sh])
  Error: 6-16 00:43:50] [ERROR] Spawned process exited abnormally (code 255; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/javascript/tools/autobuild.sh])
  A fatal error occurred: Exit status 255 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/javascript/tools/autobuild.sh]
  A fatal error occurred: Exit status 255 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/javascript/tools/autobuild.sh]
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/codeql' failed with exit code 2
  Error: The process '/opt/hostedtoolcache/CodeQL/0.0.0-20210517/x64/codeql/codeql' failed with exit code 2
      at Object.toolrunnerErrorCatcher (/home/runner/work/_actions/github/codeql-action/v1/lib/toolrunner-error-catcher.js:79:19)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Object.extractScannedLanguage (/home/runner/work/_actions/github/codeql-action/v1/lib/codeql.js:406:13)
      at async createdDBForScannedLanguages (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:64:13)
      at async finalizeDatabaseCreation (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:70:5)
      at async Object.runAnalyze (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze.js:172:5)
      at async run (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:52:30)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/analyze-action.js:106:9)